# Generated by Django 2.1.4 on 2018-12-14 14:24

import apps.file_upload.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to=apps.file_upload.models.user_directory_path)),
            ],
        ),
    ]
