# Generated by Django 2.1.4 on 2018-12-15 04:19

import apps.file_upload.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0002_mymodel_tahun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='tahun',
            field=models.IntegerField(default=apps.file_upload.models.current_year, validators=[django.core.validators.MinValueValidator(1984), apps.file_upload.models.max_value_current_year], verbose_name='tahun'),
        ),
    ]
